image: 'rust:latest'

stages:
  - info
  - test

info:
  stage: info
  script:
    - rustc --version
    - cargo --version

test:
  stage: test
  script:
    - cargo test --verbose

cache:
  paths:
    - apt/
    - cargo/
    - target/
